// This file is auto-generated by the Windows Forms Designer.
// It defines the InitializeComponent method and the controls used in the form.

namespace assignment2
{
    partial class Joke_and_PunchLine
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        private System.Windows.Forms.Label Jokelabel;
        private System.Windows.Forms.Button btnSetup;
        private System.Windows.Forms.Button btnPunchLine;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            Jokelabel = new Label();
            btnSetup = new Button();
            btnPunchLine = new Button();
            SuspendLayout();
            // 
            // Jokelabel
            // 
            Jokelabel.BackColor = Color.LightCyan;
            Jokelabel.Font = new Font("Arial Narrow", 13.8F, FontStyle.Bold, GraphicsUnit.Point, 0);
            Jokelabel.Location = new Point(82, 78);
            Jokelabel.Margin = new Padding(4, 0, 4, 0);
            Jokelabel.Name = "Jokelabel";
            Jokelabel.Size = new Size(387, 60);
            Jokelabel.TabIndex = 2;
            Jokelabel.TextAlign = ContentAlignment.MiddleCenter;
            // 
            // btnSetup
            // 
            btnSetup.BackColor = Color.Aquamarine;
            btnSetup.Font = new Font("Segoe UI", 10.2F, FontStyle.Bold, GraphicsUnit.Point, 0);
            btnSetup.Location = new Point(119, 215);
            btnSetup.Margin = new Padding(4, 5, 4, 5);
            btnSetup.Name = "btnSetup";
            btnSetup.Size = new Size(138, 46);
            btnSetup.TabIndex = 0;
            btnSetup.Text = "Show Setup";
            btnSetup.UseVisualStyleBackColor = false;
            btnSetup.Click += btnSetup__Click;
            // 
            // btnPunchLine
            // 
            btnPunchLine.BackColor = Color.MediumAquamarine;
            btnPunchLine.Font = new Font("Segoe UI", 10.2F, FontStyle.Bold, GraphicsUnit.Point, 0);
            btnPunchLine.Location = new Point(298, 215);
            btnPunchLine.Margin = new Padding(4, 5, 4, 5);
            btnPunchLine.Name = "btnPunchLine";
            btnPunchLine.Size = new Size(159, 46);
            btnPunchLine.TabIndex = 1;
            btnPunchLine.Text = "Show Punchline";
            btnPunchLine.UseVisualStyleBackColor = false;
            btnPunchLine.Click += btnPunchLine_Click;
            // 
            // Joke_and_PunchLine
            // 
            AutoScaleDimensions = new SizeF(8F, 20F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.SteelBlue;
            ClientSize = new Size(567, 362);
            Controls.Add(Jokelabel);
            Controls.Add(btnSetup);
            Controls.Add(btnPunchLine);
            Margin = new Padding(4, 5, 4, 5);
            Name = "Joke_and_PunchLine";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "Joke and PunchLine";
            ResumeLayout(false);
        }

        #endregion
    }
}